name: "Build and publish build images"

on: ['push']

jobs:
  publish-debian-amd64-image:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - name: 'Login to docker.io'
      uses: 'docker/login-action@v2'
      with:
        username: '${{ secrets.DOCKER_IO_USER }}'
        password: '${{ secrets.DOCKER_IO_PASSWORD }}'
    - run: './publish-debian-arm64.sh'
